export default ScreenNames = {
    HOME:"HOME",
    VIDEOSCREEN: "VIDEOSCREEN",
    VIDEOREORDING: "VIDEOREORDING",
    AUDIORECORDING: "AUDIORECORDING",
    TEXTFORMAT: "TEXTFORMAT",
    RESPONSELIST: "RESPONSELIST",
    PLAYRAUIDORECORD: "PLAYRAUIDORECORD"
}